### ISSUE TITLE
CI app doesn't return failure when CI_InitTbls() failed.

### ISSUE THREAD

**Issue by ynielson** [WindhoverLabs/airliner#218]
When the function  CI_InitTbls() is called,
if the unit test gives failure reason to the function call, CFE_TBL_GetAddress(),
The CI_InitTbls() returns CFE_SUCCESS instead of the failure.

**Comment by mbenson1** [comment]
Fixed.  I also added an additional check to ensure that the table address is set to zero if the function fails.
