### ISSUE TITLE
SENS app didn't write to sys log when the InitApp() function failed.

### ISSUE THREAD

**Issue by ynielson** [WindhoverLabs/airliner#273]
Sens application didn''t write to sys log 3 times when the InitApp() fucntion failed due to event registration failure.
At the end of the InitApp() function the condition to write to sys log should be "hasEvents == 0".
I think there may be more apps which copied same code at this end of InitApp function.

- Test case: Test_SENS_AppMain_Fail_InitApp
![sens_FailInitApp_2022-11-15 12-12-09](https://user-images.githubusercontent.com/102169856/201994869-ba4fd218-118a-4dee-af37-7f9064750383.png)

**Comment by mbenson1** [comment]
Good catch.  Fixed in the 241-unit-test-for-sens-application branch.
